title: Portfolio
default_lang: Ireland
author:
  name: 'Cormac Lynch'
  email: cormac.lynch@outlook.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  - '31 Hilltown Park, River Valley'
blog:
  route: /blog
